### ISSUE TITLE
Initial helper api

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-soy#3]
## Overview
This will deliver a cli and node library for developers to interact with an ens resolver #2. The cli will be a wrapper around the library to enable build scripts in bash and node. The cli will aim to allow for easy contract deployment with the goal of providing a wrapper and management of the deployed contract. 

### Acceptance
- [ ] there exists a globally installable npm cli 
- [ ] Cli is a wrapper around a fully functional node library
- [ ] The node lib can
  - Deploy a new contract
  - help set itself as a resolver?
  - Interact with an existing contract to publish new revisions
- [ ] Coverage and linting

## Tasks
- [ ] Create node lib
- [ ] Create cli wrapper

## Assumptions
- web3studio needs a standards lib for prettier/eslint etc config
- hyperlane is a monorepo (cli, core, contracts, etc)
