### ISSUE TITLE
Initial Gateway

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-soy#4]
## Overview
An initial HTTP gateway enabling ens routing of ipfs locations. Overall logic defined in the architecture #1.

### Questions
* Can `.luxe` or https://eth.show handle this?
* Can Cloudflare's _dnslink protocol do this?

### Acceptance
- Users can access their website resolve from ens over HTTP

**Nice to haves**
These are things that the architecture wants but isn't necessary for the first push. If these can't be accomplished easily, note in this issue what prevents it and or any workarounds.

- custom domains 
- time traveling across revisions 

## Tasks
- [ ] Investigate possible services that will do this for us
- [ ] Test resolver with existing gateways (cloudflare, eth.show), see if we can use them 
- [ ] reEvaluate and break this down based on answers.

## Assumptions
