### ISSUE TITLE
Getting Started experience 

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-soy#44]
## Overview

As a developer-user, I want to be able to quickly spin up a simple site using Soy so that they can see it's simplicity and usefulness.

### Reference

- [Reference](links)
- [To issues](or any inspiration)
- [That might be](helpful)

### Questions

- How can we streamline ENS registration?
- How can we streamline eth for app-payments? 
    - Do we want to attempt to use something like [fuel networks](https://github.com/ahmb84/fuel-web3-provider)?

### Assumptions

- we have `madewith.eth` to hand out subdomains of

### Acceptance

- Users can put an existing static site on soy in under 5 min. 

## Tasks

- [ ] Understand where the bottlenecks of first time set up are
- [ ] Patch obvious holes that can be fixed
- [ ] Plan any upcoming work
- [ ] ???
- [ ] Profit
