### ISSUE TITLE
Move soy gateway to mainnet

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-soy#45]
## Overview

As a developer using soy, I want the protections and tamper-proofing capabilities that main net gives, so that I can have assurance that my website deployed stays there.

### Reference
- Depends #41 for permissioning etc.

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- Web3Studio will be deployed to Rinkby, it needs to be moved first
- In "production" the app should have just-enough protections but nothing over the top
- Lightweight monitoring to know when gateway is down or acting up
- Monitoring done with cloudwatch => Slack

### Acceptance

- web3studio.eth.soy shows the build of webstudio-website refereincing the contract on mainnet. 
- Dev team is notified via slack if the website is down or acting up. 

## Tasks

- [x] Add monitoring to consensys.net/web3studio/
- [x] Add monitoring to web3studio.eth.soy/web3studio/
- [x] Deploy soy-contracts to mainnet and update rinkby and ropsten
    - Update soy contract `deployed` addrs (Can the build do this? maybe with a 
- [x] Configure website health check deployment to point to prod
- [x] Configure soy health check and SAM deployment to point to prod
    - Move the domain across accountshard coded migration contract?)
- [x] Register web3studio.eth.soy to mainnet SoyPublicResolver
- [x] Configure gateway to point at mainnet
- [x] Publish story on Medium
- [x] Update Website to include collection project

**Comment by barlock** [comment]
Issues to open:
* Harmonization with the larger consensys.net navigation (somehow?)
* Review the website with catalyst
    * Probably need to update the site to larger .net ecosystem before the meeting
* Checkout segment.io for better analytics funneling and analyzing


@barlock ☝️
