### ISSUE TITLE
Setup monorepo with standards

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-soy#5]
## Overview
As a developer, I want this project to have project standards set by the team enforced automatically

### Assumptions
- config for standards should be in an installable library. (@web3studio/standards or otherwise)

### Acceptance
- Linting via eslint
- Prettier 

## Tasks
- [ ] Create standards repo
- [ ] Setup lerna monorepo
- [ ] Setup eslint and prettier with husky for git commits
