### ISSUE TITLE
Investigate existing gatways

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-soy#8]
## Overview
As a soy developer, I want to understand how ens resolvers work with existing gateways so that I can understand what changes need to be made, if any, to make soy successful.

### Questions
- What gateway services exist?
- How do you map custom domains to the services? 
- What kind of latency exists for existing gateways? Around the world?
- time traveling capabilities?

### Acceptance
- List in this issue of investigated services and outcomes

## Tasks
- [ ] Find and list services
- [ ] answer questions per service
- [ ] Create recommendation for #4
